### ISSUE TITLE
[OAuth client]Support for updating a client

### ISSUE THREAD

**Issue by thtri** [cxpsemea/Cx1ClientGo#146]
Hello, 

We wanted to update an existing client (e.g., add a Distribution List or an email to the Notification list).
However, there is no method to update (PUT) a client whereas there exists methods for GET/POST/DELETE a client. 
Is it possible to make this one public https://github.com/cxpsemea/Cx1ClientGo/blob/main/clients.go#L155 ?

thanks,

**Comment by thtri** [comment]
@michaelkubiaczyk FYI

**Comment by michaelkubiaczyk** [comment]
hi @thtri I have made this saveClient call public (SaveClient) but there is a gotcha: it was not meant to be public since it is not using the OIDC client struct's values, but instead there is an internal "oidcclientraw map[string]interface{}" storing the raw json returned by the API, so any changes using this SaveClient have to be done on the oidcclientraw member itself. Changes to the custom exposed variables will not be saved.

I think the proper solution would be to map out the various fields in the oidc client and add them to the oidc client object properly, however as the 'attributes' are defined server-side by Checkmarx these can change and I may not have a full list of existing attributes. Likewise there seem to be fields on the main oidc client object that have appeared over time, eg I believe "rootUrl" and "adminUrl" fields were not there previously. Consequently there may be new fields that are introduced that won't be included in cx1clientgo, and the PUT request updating the oidc client may cause unintended side effects if that field is missing (since it is not a PATCH). 

So I think there are two options:
1. continue as-is, with some fields exposed in the client directly due to common utilization, and others hidden behind this "oidcclientraw" map
2. make the whole oidcclient object itself into a map[string]interface{} so it can be used easily, but then there will be no exposed fields with nice names. Currently it is just the "ClientSecretExpiry", and "Creator" fields that I've exposed directly on the object, they map to the client.attributes[client.secret.expiration.time] and client.attributes[creator] fields. I could add some get/set functions to wrap setting these attributes for convenience.

What do you think?

**Comment by thtri** [comment]
@michaelkubiaczyk hi, thanks for the explanation. Option 1) sounds good. Thanks!
